include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    directives_ordering: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    require_trailing_commas: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
